CREATE TABLE SEMIPRECIOUS (
    ID INT NOT NULL,
    NAME VARCHAR(50) NOT NULL,
    OPACITY DOUBLE NOT NULL,
    PRICE INT NOT NULL,
    PRIMARY KEY( ID )
);

INSERT INTO SEMIPRECIOUS VALUES(1, 'amber', 0.7, 100);
INSERT INTO SEMIPRECIOUS VALUES(2, 'apatite', 0.65, 140);
INSERT INTO SEMIPRECIOUS VALUES(3, 'rhodochrosis', 0.82, 95);
INSERT INTO SEMIPRECIOUS VALUES(4, 'euclase', 0.42, 210);

CREATE TABLE GEMSTONE (
    ID INT NOT NULL,
    NAME VARCHAR(50) NOT NULL,
    OPACITY DOUBLE NOT NULL,
    CARATS INT NOT NULL,
    PRICE INT NOT NULL,
    PRIMARY KEY( ID )
);

INSERT INTO GEMSTONE VALUES(1, 'diamond', 0.15, 12, 10000);
INSERT INTO GEMSTONE VALUES(2, 'emerald', 0.5, 7, 14500);
INSERT INTO GEMSTONE VALUES(3, 'ruby', 0.52, 14, 8200);
INSERT INTO GEMSTONE VALUES(4, 'sapphire', 0.37, 9, 17100);
